const universities = [
	// {id: "ASU_123456", name: "Ain Shams University", abbreviation: "ASU"},
	// {id: "AZU_789012", name: "Al-Azhar University", abbreviation: "AZU"},
	// {id: "ALEXU_345678", name: "Alexandria University", abbreviation: "ALEXU"},
	// {id: "AUN_567890", name: "Assiut University", abbreviation: "AUN"},
	// {id: "ASWU_234567", name: "Aswan University", abbreviation: "ASWU"},
	// {id: "BU_890123", name: "Banha University", abbreviation: "BU"},
	// {id: "BSU_456789", name: "Beni-Suef University", abbreviation: "BSU"},
	// {id: "CU_012345", name: "Cairo University", abbreviation: "CU"},
	// {id: "DAU_678901", name: "Damanhour University", abbreviation: "DAU"},
	// {id: "DU_234567", name: "Damietta University", abbreviation: "DU"},
	// {id: "E-JUST_890123", name: "Egypt-Japan University of Science and Technology", abbreviation: "E-JUST"},
	// {id: "FU_456789", name: "Fayoum University", abbreviation: "FU"},
	// {id: "HU_012345", name: "Helwan University", abbreviation: "HU"},
	// {id: "KFS_678901", name: "Kafrelsheikh University", abbreviation: "KFS"},
	// {id: "LU_234567", name: "Luxor University", abbreviation: "LU"},
	// {id: "MANS_890123", name: "Mansoura University", abbreviation: "MANS"},
	// {id: "MTC_456789", name: "Military Technical College", abbreviation: "MTC"},
	// {id: "Minia_012345", name: "Minia University", abbreviation: "-"},
	// {id: "Minufiya_678901", name: "Minufiya University", abbreviation: "-"},
	// {id: "NVU_234567", name: "New Valley University", abbreviation: "NVU"},
	// {id: "PSU_890123", name: "Port Said University", abbreviation: "PSU"},
	// {id: "SAMS_456789", name: "Sadat Academy for Management Sciences", abbreviation: "SAMS"},
	// {id: "SO_012345", name: "Sohag University", abbreviation: "SO"},
	// {id: "SVU_678901", name: "South Valley University", abbreviation: "SVU"},

	{id: "SCU_234567", name: "Suez Canal University", abbreviation: "SCU"},

	// {id: "SU_890123", name: "Suez University", abbreviation: "SU"},
	// {id: "TU_456789", name: "Tanta University", abbreviation: "TU"},
	// {id: "USC_012345", name: "University of Sadat City", abbreviation: "USC"},
	// {id: "ZU_678901", name: "Zagazig University", abbreviation: "ZU"},
	// {id: "ZC_234567", name: "Zewail City of Science, Technology and Innovation", abbreviation: "ZC"},
	// {id: "KSIU_890123", name: "King Salman International University", abbreviation: "KSIU"},
	// {id: "GU_456789", name: "Galala University", abbreviation: "GU"},
	// {id: "AIU_012345", name: "AlAlamein International University", abbreviation: "AIU"},
	// {id: "NMU_678901", name: "New Mansoura University", abbreviation: "NMU"},
	// {id: "EUI_234567", name: "Egypt University Of Informatics", abbreviation: "EUI"},
	// {id: "NU_890123", name: "Nile University", abbreviation: "NU"},
	// {id: "GIU_456789", name: "German International University", abbreviation: "GIU"},
	// {id: "GUC_012345", name: "German University in Cairo", abbreviation: "GUC"},
	// {id: "ACU_678901", name: "Ahram Canadian University", abbreviation: "ACU"},
	// {id: "AUC_234567", name: "The American University in Cairo", abbreviation: "AUC"},
	// {id: "AOU_890123", name: "Arab Open University", abbreviation: "AOU"},
	// {id: "BUE_456789", name: "British University in Egypt", abbreviation: "BUE"},
	// {id: "CIC_012345", name: "Canadian International College", abbreviation: "CIC"},
	// {id: "DUST_678901", name: "Delta University for Science and Technology", abbreviation: "DUST"},
	// {id: "ECU_234567", name: "Egyptian Chinese University", abbreviation: "ECU"},
	// {id: "EELU_890123", name: "Egyptian e-Learning University", abbreviation: "EELU"},
	// {id: "ERU_456789", name: "Egyptian Russian University", abbreviation: "ERU"},
	// {id: "FUE_012345", name: "Future University in Egypt", abbreviation: "FUE"},
	// {id: "HU_678901", name: "Heliopolis University", abbreviation: "HU"},
	// {id: "MIU_234567", name: "Misr International University", abbreviation: "MIU"},
	// {id: "MUST_890123", name: "Misr University for Science and Technology", abbreviation: "MUST"},
	// {id: "UH_456789", name: "Hertfordshire University In Egypt", abbreviation: "UH"},
	// {id: "MSA_012345", name: "Modern Sciences and Arts University", abbreviation: "MSA"},
	// {id: "MTI_678901", name: "MTI University", abbreviation: "MTI"},
	// {id: "NUB_234567", name: "Nahda University in Beni Suef", abbreviation: "NUB"},
	// {id: "O6U_890123", name: "October 6 University", abbreviation: "O6U"},
	// {id: "PUA_456789", name: "Pharos University in Alexandria", abbreviation: "PUA"},
	// {id: "SU_012345", name: "Sinai University", abbreviation: "SU"},
	// {id: "UFE_678901", name: "French University of Egypt", abbreviation: "UFE"},
	// {id: "BUC_234567", name: "Badr University in Cairo", abbreviation: "BUC"},
	// {id: "BUA_890123", name: "Badr University in Assiut", abbreviation: "BUA"},
	// {id: "NGU_456789", name: "New Giza University", abbreviation: "NGU"},
	// {id: "SHA_012345", name: "El Shorouk Academy", abbreviation: "SHA"},
	// {id: "TMU_678901", name: "Toronto Metropolitan University Cairo", abbreviation: "TMU"},
	// {id: "UPEI_234567", name: "University of Prince Edward Island", abbreviation: "UPEI"},
];

export default universities;
